[package]
name = "prost-reflect"
description = "A protobuf library extending prost with reflection support and dynamic messages."
version = "0.1.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/prost-reflect"
documentation = "https://docs.rs/prost-reflect"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
autotests = false
rust-version = "1.53.0"

[workspace]
members = ["tests"]

[features]
serde = ["serde1", "base64"]

[dependencies]
prost = "0.9.0"
prost-types = "0.9.0"
serde1 = { package = "serde", version = "1.0.132", optional = true }
base64 = { version = "0.13.0", optional = true }

[dev-dependencies]
