[package]
name = "prost-reflect"
description = "A protobuf library extending prost with reflection support and dynamic messages."
keywords = ["protobuf", "serialization", "json"]
categories = ["encoding"]
version = "0.2.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/prost-reflect"
documentation = "https://docs.rs/prost-reflect"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
autotests = false
rust-version = "1.53.0"
exclude = [".github", "src/file_descriptor_set.bin"]

[workspace]
members = ["tests"]

[features]
serde = ["serde1", "base64", "chrono"]

[dependencies]
base64 = { version = "0.13.0", optional = true }
chrono = { version = "0.4.19", optional = true, default-features = false, features = [
    "std"
] }
prost = "0.9.0"
prost-types = "0.9.0"
serde1 = { package = "serde", version = "1.0.132", optional = true }

[dev-dependencies]
serde_json = "1.0.73"

[package.metadata.docs.rs]
all-features = true
