[package]
name = "prost-reflect"
description = "prost-reflect."
version = "0.0.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/prost-reflect"
documentation = "https://docs.rs/prost-reflect"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
autotests = false

[workspace]
members = ["tests"]

[dependencies]
prost = "0.9.0"
prost-types = "0.9.0"

[dev-dependencies]
